const certificates = [
    {
      id: 1,
      title: "Basic of Pharma",
      percentage: 100,
      stage: "Stage 1-5",
      completedStages: 5,
      trainer: "Dr. Sarah Johnson",
      date: "15 Apr 2025 Thursday",
      time: "09:00 AM",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
      tags: ["Integrity", "Pharmacy", "Research"],
      details: {
        studentsEnrolled: 45,
        AssignTeacher: "Dr. Sarah Johnson",
        category: "Pharmacy",
        location: "Himmel",
        timing: "09:00 AM - 11:00 AM",
        titles: "Details",
      },
    },
    {
      id: 2,
      title: "Pharmaceutical Chemistry",
      percentage: 65,
      stage: "Stage 1-5",
      completedStages: 2,
      trainer: "Dr. Michael Chen",
      date: "20 Apr 2025 Tuesday",
      time: "10:00 AM",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
      tags: ["Chemistry", "Analysis", "Research"],
      details: {
        studentsEnrolled: 38,
        AssignTeacher: "Dr. Michael Chen",
        category: "Chemistry",
        location: "Himmel",
        timing: "10:00 AM - 12:00 PM",
        titles: "Details",
      },
    },
    {
      id: 3,
      title: "Clinical Pharmacy",
      percentage: 92,
      stage: "Stage 1-5",
      completedStages: 4,
      trainer: "Dr. Emily Roberts",
      date: "22 Apr 2025 Thursday",
      time: "01:00 PM",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
      tags: ["Clinical", "Patient Care", "Ethics"],
      details: {
        studentsEnrolled: 32,
        AssignTeacher: "Dr. Emily Roberts",
        category: "Clinical",
        location: "Himmel",
        timing: "01:00 PM - 03:00 PM",
        titles: "Details",
      },
    },
    {
      id: 4,
      title: "Pharmaceutical Regulations",
      percentage: 42,
      stage: "Stage 1-5",
      completedStages: 2,
      trainer: "Prof. David Wilson",
      date: "25 Apr 2025 Monday",
      time: "09:00 AM",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
      tags: ["Regulations", "Compliance", "Guidelines"],
      details: {
        studentsEnrolled: 40,
        AssignTeacher: "Prof. David Wilson",
        category: "Regulations",
        location: "Himmel",
        timing: "09:00 AM - 11:00 AM",
        titles: "Details",
      },
    },
    {
      id: 5,
      title: "Pharmacology Advanced",
      percentage: 75,
      stage: "Stage 1-5",
      completedStages: 3,
      trainer: "Dr. Lisa Thompson",
      date: "28 Apr 2025 Thursday",
      time: "02:00 PM",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
      tags: ["Pharmacology", "Research", "Advanced"],
      details: {
        studentsEnrolled: 35,
        AssignTeacher: "Dr. Lisa Thompson",
        category: "Pharmacology",
        location: "Himmel",
        timing: "02:00 PM - 04:00 PM",
        titles: "Details",
      },
    },
    {
      id: 6,
      title: "Pharmaceutical Manufacturing",
      percentage: 50,
      stage: "Stage 1-5",
      completedStages: 2,
      trainer: "Prof. Robert Adams",
      date: "30 Apr 2025 Monday",
      time: "10:00 AM",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
      tags: ["Manufacturing", "Quality", "GMP"],
      details: {
        studentsEnrolled: 42,
        AssignTeacher: "Prof. Robert Adams",
        category: "Manufacturing",
        location: "Himmel",
        timing: "10:00 AM - 12:00 PM",
        titles: "Details",
      },
    },
  ]

  export default certificates