export const courses = [
    {
      id: 1,
      title: "Clinical Pharmacy-II",
      code: "CP-102",
      description: "Advanced clinical pharmacy concepts and patient care",
      trainer: "Dr. Sarah Johnson",
      date: "2025-01-15",
      time: "08:00 AM",
      progress: 75,
      status: "in-progress",
      type: "mandatory",
      category: "pharmacy",
      lastAccessed: "2025-01-10",
      dueDate: "2025-02-15",
      startDate: "2025-01-01",
      studentsEnrolled: 22,
      location: "Room 101",
      timing: "10:00 AM - 12:00 PM",
      duration: "4 hours",
      modules: 8,
      completedModules: 6,
      tags: ["Clinical", "Patient Care", "Advanced"],
      image: "/clinical-pharmacy-course.jpg",
      materials: [
        { name: "Course Handbook", type: "PDF", size: "2.5 MB" },
        { name: "Video Lectures", type: "Video", duration: "3.5 hours" },
        { name: "Practice Exercises", type: "Interactive", count: "15 exercises" },
      ],
    },
    {
      id: 2,
      title: "Pharmaceutical Chemistry Fundamentals",
      code: "PC-101",
      description: "Basic principles of pharmaceutical chemistry and drug development",
      trainer: "Prof. Michael Chen",
      date: "2025-01-20",
      time: "10:00 AM",
      progress: 45,
      status: "in-progress",
      type: "mandatory",
      category: "chemistry",
      lastAccessed: "2025-01-08",
      dueDate: "2025-03-01",
      startDate: "2025-01-05",
      studentsEnrolled: 28,
      location: "Lab 205",
      timing: "2:00 PM - 4:00 PM",
      duration: "6 hours",
      modules: 10,
      completedModules: 4,
      tags: ["Chemistry", "Drug Development", "Fundamentals"],
      image: "/pharmaceutical-chemistry-lab.jpg",
      materials: [
        { name: "Lab Manual", type: "PDF", size: "3.2 MB" },
        { name: "Chemical Structures Guide", type: "PDF", size: "1.8 MB" },
        { name: "Virtual Lab Simulations", type: "Interactive", count: "12 simulations" },
      ],
    },
    {
      id: 3,
      title: "Healthcare Ethics and Law",
      code: "HE-201",
      description: "Ethical principles and legal frameworks in healthcare practice",
      trainer: "Dr. Emily Rodriguez",
      date: "2025-02-01",
      time: "02:00 PM",
      progress: 100,
      status: "completed",
      type: "elective",
      category: "ethics",
      lastAccessed: "2025-01-05",
      dueDate: "2025-01-30",
      startDate: "2024-12-01",
      studentsEnrolled: 15,
      location: "Auditorium A",
      timing: "2:00 PM - 3:30 PM",
      duration: "3 hours",
      modules: 6,
      completedModules: 6,
      tags: ["Ethics", "Legal", "Healthcare"],
      image: "/healthcare-ethics-course.jpg",
      materials: [
        { name: "Ethics Case Studies", type: "PDF", size: "4.1 MB" },
        { name: "Legal Framework Guide", type: "PDF", size: "2.7 MB" },
        { name: "Discussion Forums", type: "Interactive", count: "8 discussions" },
      ],
    },
   
  ]
  
  