export const notificationsData = [
    {
      id: 2,
      title: "Course Progress Update",
      description: "Phase 1 - Foundation Concepts",
      date: "Continue Learning",
      progress: 45,
      type: "course",
      phase: 1,
      link: "/learner-dashboard/courses",
    },
    {
      id: 3,
      title: "Course Progress Update",
      description: "Phase 2 - Advanced Topics",
      date: "Continue Learning",
      progress: 60,
      type: "course",
      phase: 2,
      link: "/learner-dashboard/courses",
    },
    {
      id: 4,
      title: "Course Assignment Due",
      description: "Complete your assignment for Phase 3",
      date: "Due Tomorrow",
      progress: 75,
      type: "assignments",
      phase: 3,
      link: "/learner-dashboard/assignments",
      isAssignment: true,
    },
    {
      id: 5,
      title: "Course Quiz Available",
      description: "Take your quiz for Phase 4",
      date: "Available Now",
      progress: 90,
      type: "assignments",
      phase: 4,
      link: "/learner-dashboard/assignments",
      isQuiz: true,
    },
    {
      id: 6,
      title: "New Course Material",
      description: "Phase 5 content has been released",
      date: "Check it out",
      progress: 20,
      type: "course",
      phase: 5,
      link: "/learner-dashboard/courses",
    },
    {
      id: 7,
      title: "Discussion Forum",
      description: "New replies to your discussion thread",
      date: "Join Discussion",
      progress: null,
      type: "discussion",
      link: "/learner-dashboard/discussions",
    },
  ]